version: '3.7'
services:
  obj_seg:
    container_name: obj_seg 
    restart: always
    build: .
    ports:
      - 9494:9494
    volumes:
      - ${MODEL_PATH}:/app/demo/model.pth
    command: bash -c "cd demo && python obj_seg.py --config_file docker.yaml"